### ISSUE TITLE
Week 03 - Day 4 - Tic Tac Toe

### ISSUE THREAD

**Issue by gstark** [TobiasNorton/Assignments#11]
With a partner, create a design for a tic-tac-toe game. Practice your technical design skills (i.e. thinking about _how_ you would code this).

## Objectives

- Plan and design "ideas"
- Collaborate and communicate effectively around technical ideas
- Implement code together with a partner

## Requirements

Features to consider:

- [x] Game should be played on the same computer.
- [x] As a user, I should be able to see a tic-tac-toe board.
- [x] As a user, the game should alternate turns, between `X` and `O`.
- [x] As a user, I should be able to click in a square and play either `X` or `O`, respective of the turn.
- [x] As a user, when I get three in a row, I should be told I've won and the game should be over.

**TIPS:**

- These designs should be so detailed that you could give them another team and they could implement it with few (if any) questions.
- If at any time you want to validate a piece of your design (e.g. the algorithm, event handling, or UI/UX), you can create an _extremely simple_ site that proves or disproves your idea.

### Explorer Mode

WITH your partner: submit a full design of how to approach this problem. This should include:

- [x] A digital mock up (created using software, or a photo/scan of an analog drawing)
- [x] Implementation details, such as how you are implementing each square
- [x] A list of events you are listening for
- [x] _psuedo-code_ describing your program (e.g. event-handling, game logic)

Finally, also with your partner:
- [x] Create your tic-tac-toe game!

### Adventure Mode

- [ ] Plan the implementation of a "vs computer" mode, that picks a random square.

_or_

- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable.

### Epic Mode

- [ ] Modify your "vs computer" mode to follow a specific strategy (of your choice).

## Additional Resources

- [PEDAC](https://medium.com/launch-school/solving-coding-problems-with-pedac-29141331f93f)
- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups and prototypes.
- Read about [Pseudocode](https://en.wikipedia.org/wiki/Pseudocode)

**Comment by TobiasNorton** [comment]
Explorer mode for Dylan and me
https://github.com/TobiasNorton/tic-tac-toe

**Comment by gstark** [comment]
Please have Dylan turn in the same repo, or have him `fork` your repo and turn in his forked repository copy.

**Comment by TobiasNorton** [comment]
Fixed a mistake that Dylan and I just caught
https://github.com/TobiasNorton/tic-tac-toe

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--337d5db9d88e083c06c448999f852548342972b5/giphy-18.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/83)**__

**Comment by gstark** [comment]
See if you can go back and refactor the fillBoxSevenWithLetter style methods into a single method.

Also an array for playerOneArray and playerTwoArray is likely not the best type of variable to store this information in.
