### ISSUE TITLE
Week 05 - Day 2 - JavaScript Iteration

### ISSUE THREAD

**Issue by gstark** [TobiasNorton/Assignments#16]
# JavaScript Iteration

## Objectives

After completing this assignment, you should be able to:

* Demonstrate an understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/js-iteration) to your own account.
2. Change into your projects directory:
3. Clone your repository: `git clone js-iteration`
4. Change into your project's directory: `cd js-iteration`
5. Install the dependencies: `yarn install` (or just `yarn` for short)
6. Open in your editor]
7. Start the test runner: `yarn test`
7. Open `src/functions.test.js` and work on functions until tests pass.
8. Commit and push your work to GitHub.
9. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation on DevDocs to find what kind of helpful functions might already be in JavaScript.

- [String Functions on DevDocs](https://devdocs.io/javascript/global_objects/string).
- [Array Functions on DevDocs](http://devdocs.io/javascript/global_objects/array).

**Comment by TobiasNorton** [comment]
https://github.com/TobiasNorton/js-iteration

**Comment by gstark** [comment]
Great work!

Try using the method `find` for `findTheNeedle`

and

```
if (evenNumberArray.length === numberArray.length) {
    return true
  } else {
    return false
  }
```

can just be  `return evenNumberArray.length === numberArray.length`

There is also a simpler way to implement this. Try thinking of another algorithm and try it again.

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Excellent ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7011f587540879473d89b0a7000ad6667e699c22/exceeds-2.gif)
> &ldquo;Excellent &rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/64)**__
