### ISSUE TITLE
Week 05 - Day 3 - Thanksgiving Break Assignment

### ISSUE THREAD

**Issue by gstark** [TobiasNorton/Assignments#17]
# Choose one or more of the following:
- Try the [Javascript Koans](https://github.com/suncoast-devs/koans)
- Implement Blackjack in React
- Implement Tic-Tac-Toe in React
- Implement [this homework](https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman/)
- Go through the free [Javascript 30](https://javascript30.com)

# Videos to Watch
- Watch this [amazing video](https://vimeo.com/36579366)

**Comment by TobiasNorton** [comment]
Koans:
https://github.com/TobiasNorton/koans

I got the Snowman functioning but I'm having trouble extracting components. I'll have to finish it at another time. Here's what I have:
https://github.com/TobiasNorton/snowman

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Woah](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d5eae07a7d338c96b9a2cc704bc5ec7f53d072c/woah.gif)
> &ldquo;Woah&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/2)**__
