### ISSUE TITLE
Week 02 - Day 2 - Roshambo

### ISSUE THREAD

**Issue by gstark** [TobiasNorton/Assignments#6]
Create a simple Rock-Paper-Scissors game.

## Objectives

- Work with JavaScript and the DOM
- Practice conditional logic

## Requirements

Do not worry about CSS for explorer mode, only do as HTML to show the functionality.

### Background

See the wikipedia page about [Rock, Paper, Scissors](https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors)

### How to get started

- Get familiar with rock, paper, scissors if you haven't played before (or in a while)
- Draw out on paper/whiteboard/computer the rough design of your application
  - See _Explorer Mode_ for the UI requirements
- Start by placing all the HTML elements on the page
- Style the user interface
- Write out in English, ALL the steps the application needs to take
  - For example "When user one clicks on Rock, remember that user one chooses Rock"
- Start adding JavaScript to make your program to do the steps you described above

### Explorer Mode

- [x] As a user I should be able to see three buttons for each player.
- [x] As a user, I should be able to pick an option for each player.
- [x] As a user, after each player makes their selection, I should be told who won and the game should be over.

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection.
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice)
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Your game is currently only 1 vs 1, add the ability to add more computer or users players to the game

**Comment by TobiasNorton** [comment]
https://github.com/TobiasNorton/roshambo

**Comment by gstark** [comment]
Nicely done! My only comment is to please not leave commented out code in your submitted work. 

Unless the code is there for a reason and commented out it is better to submit a "clean" copy. An example would be "I tried this approach and it didn't work for this reason: _________"

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
